### ISSUE TITLE
Can't Use React Native Web Maps LoadScript With Props libraries

### ISSUE THREAD

**Issue by ishaqadhel** [preflower/react-native-web-adapter#31]
Hi, on react native web maps,  when I want to use props libraries, the type is not exported and doesn't support string how do I use loadscript with libraries props? I need it to use the places libraries from the google maps api. Thank you.

![Screen Shot 2022-03-28 at 11 38 47](https://user-images.githubusercontent.com/49280352/160327551-7c498b2e-1e49-42e5-adb7-8b9595641db9.png)
![Screen Shot 2022-03-28 at 11 38 36](https://user-images.githubusercontent.com/49280352/160327584-f564863e-fc9a-444b-88a4-205b23d8ae06.png)

**Comment by preflower** [comment]
libraries need array type
use `['places']` instead of it

**Comment by preflower** [comment]
and i will export `@react-google-maps/api` types in next version

**Comment by preflower** [comment]
new version has exported `@react-google-maps/api` apis

**Comment by ishaqadhel** [comment]
Thank you so much! 😊
